; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:4d_systems_esp32s3_gen4_r8n16]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
upload_port = COM4
; monitor_speed = 115200
; monitor_port = COM4
; board_build.psram = enabled

; 添加 AUTOSAR 架构的头文件目录
build_flags =
    -Isrc

    -Isrc/App/CAN
    -Isrc/App/LVGL
    -Isrc/App/Audio
    -Isrc/App/AI

    -Isrc/Service/DeepSeekApi
    -Isrc/Service/CanService/CAN
    -Isrc/Service/CanService/CanNetworkService
    -Isrc/Service/SensorState
    -Isrc/Service/Utils
    -Isrc/Service/LedService
    -Isrc/Service/VoiceAssistant
    -Isrc/Service/BaiduApi
    -Isrc/Service/NetworkService
    -Isrc/Service/GUI      ; <--- 新增
    -DLV_CONF_INCLUDE_SIMPLE=1       ; <--- 告诉 LVGL 启用自定义配置
    
    -Isrc/Service/GUI/SmartGreenhouse/generated      ; <--- 新增
    -Isrc/Service/GUI/SmartGreenhouse/custom      ; <--- 新增

    -Isrc/ECUAL/INMP441
    -Isrc/ECUAL/MAX98357AETE
    -Isrc/ECUAL/Display    ; <--- 新增

    -Isrc/MCAL/NetworkAbstraction
    -Isrc/MCAL/I2S

    -Isrc/BSP/Os_Service

    -Isrc/Config

    ; -D USE_ESP_IDF_LOG
    -D CORE_DEBUG_LEVEL=4
    
build_src_filter = 
    +<*>                     ; 第一步：默认包含源目录（通常是 src）下的所有文件 
    -<Service/GUI/SmartGreenhouse/import>  
    -<Service/GUI/SmartGreenhouse/lib>   
    -<Service/GUI/SmartGreenhouse/lvgl>    
    -<Service/GUI/SmartGreenhouse/lvgl-simulator>     
    -<Service/GUI/SmartGreenhouse/temp>     

lib_deps = 
    bblanchon/ArduinoJson@^6.21.3
    https://github.com/tzapu/WiFiManager.git
    fastled/FastLED @ ^3.6.0
    lovyan03/LovyanGFX @ ^1.1.12  ; <--- 新增这行：LovyanGFX 驱动库
    paulstoffregen/XPT2046_Touchscreen
    lvgl/lvgl @ ~9.3.0  ; <--- 新增这行，指定 9.3.x 版本

; 【核心魔法】监视器过滤器
monitor_filters = 
    time           ; 每行 Log 自动加上时间戳 (超好用)
    send_on_enter  ; 敲完回车才把一整行字符串发出去 (解决无法输入长指令的问题)
    ; hexlify      ; 如果你想看十六进制数据，把这行取消注释

monitor_echo = yes

extra_scripts = pre:build_middleware.py
